[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/auth/callback"
  to   = "/.netlify/functions/auth-callback"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[build]
  publish   = "."
  functions = "netlify/functions"
